/**
 *  @file Zotero Collections Mappings
 *  @author Avana Vana <avana@esovdb.org>
 *  @module mappings
 */

module.exports = {
  /** @constant {Map} parentCollections - Maps parent collections names from the ESOVDB to parent collection IDs in the Zotero library */
  parentCollections: new Map([
    ['series', 'HYQEFRGR'],
    ['topics', 'BCQLGFXZ'],
    ['formats', '3CLRI56S'],
    ['tags', 'D8WXS5QM']
  ]),

  /** @constant {Map} topics - Maps ESOVDB video topics to their collection keys in Zotero */
  topics: new Map([
    ['Mantle Geodynamics, Geochemistry, Convection, Rheology, & Seismic Imaging and Modeling', 'B5X8MVCK'],
    ['Igneous & Metamorphic Petrology, Volcanism, & Hydrothermal Systems', 'KXQG7TMT'],
    ['Alluvial, Pluvial & Terrestrial Sedimentology, Erosion & Weathering, Geomorphology, Karst, Groundwater & Provenance', 'V8I78D2H'],
    ['Early Earth, Life\'s Origins, Deep Biosphere, and the Formation of the Planet', 'L4SALFT8'],
    ['Geological Stories, News, Tours, & Field Trips', 'SGBYID8N'],
    ['History, Education, Careers, Field Work, Economic Geology, & Technology', 'CXHVI9V2'],
    ['Glaciation, Atmospheric Science, Carbon Cycle, & Climate', 'FDY7EJ8V'],
    ['The Anthropocene', 'K9SFXQHJ'],
    ['Geo-Archaeology', 'TZE9CCSM'],
    ['Paleoclimatology, Isotope Geochemistry, Radiometric Dating, Deep Time, & Snowball Earth', 'AH3P8UQB'],
    ['Seafloor Spreading, Oceanography, Paleomagnetism, & Geodesy', 'BNKPMCWG'],
    ['Tectonics, Terranes, Structural Geology, & Dynamic Topography', 'N96Q2P6H'],
    ['Seismology, Mass Wasting, Tsunamis, & Natural Disasters', 'I2GP8YUQ'],
    ['Minerals, Mining & Resources, Crystallography, & Solid-state Chemistry', '7GA4BWHF'],
    ['Marine & Littoral Sedimentology, Sequence Stratigraphy, Carbonates, Evaporites, Coal, Petroleum, and Mud Volcanism', '5VEL36SF'],
    ['Planetary Geology, Impact Events, Astronomy, & the Search for Extraterrestrial Life', 'B3N9IR6X'],
    ['Paleobiology, Mass Extinctions, Fossils, & Evolution', 'YGF9LJ2V']
  ]),

  /** @constant {Map} formats - Maps ESOVDB video formats to their collection keys in Zotero */
  formats: new Map([
    ['Documentary Film', 'MV4V7PF9'],
    ['Documentary Series', '4GCM3HVT'],
    ['Web Series', '8TEAT23B'],
    ['Short Film', '9F6QAX8A'],
    ['Lecture Recording', '8TRG9SUC'],
    ['Multiple Lecture Recording', '5KQ8MNNK'],
    ['Lecture & Panel Discussion Recording', 'TVNS7XSN'],
    ['Webinar', 'ZYD659LC'],
    ['Course', 'YEZKPWJ5'],
    ['Debate', '6PXVK5V9'],
    ['Interview', '7NG49SMQ'],
    ['Field Trip', '82GGF7RY'],
    ['Vlog', '6Y9DPY9L'],
    ['Podcast', 'KRTG2Y7W']
  ]),

  /** @constant {Map} seriesSections - Maps ESOVDB video series' parent categories' parent collections to their collection keys in Zotero */
  seriesSections: new Map([
    [ 'TV Documentary Series', 'GAD8P2KS' ],
    [ 'Academic/Institutional Lecture Series', 'QHP6UUJC' ],
    [ 'Conference/Seminar/Workshop/Festival', 'B3JXILP2' ],
    [ 'University Course', 'NEKFWTRH' ],
    [ 'Radio Show/Podcast', 'S24JV86K' ],
    [ 'Special Event', '56BPCZSZ' ],
    [ 'Webinar/Webcast Series', 'XM997XL7' ],
    [ 'DVD/VHS', 'S6WKS3TC' ],
    [ 'Archival Video', '8RCT6S6X' ],
    [ 'Professional Course', 'UWLVJ5E4' ],
    [ 'Professional Lecture Series', 'YEAQXWS7' ],
    [ 'Internet Course', '74SLR9IC' ],
    [ 'Uncategorized', 'RDK2QRF8' ]
  ]),

  /** @constant {Map} tagSections - Maps ESOVDB video tags' parent categories' parent collections to their collection keys in Zotero */
  tagSections: new Map([
    ['Geology', 'BWD3AUB3'],
    ['Misc', 'P57IIL2F'],
    ['Petrology', '93Q83ACC'],
    ['Geological Regions', 'QD48SYT3'],
    ['Geography', 'KBLIB9IT'],
    ['Sciences', 'NPCFS6M3'],
    ['Geological Formations', 'S7U6Y3HU'],
    ['Ecology', 'CNUD2XK6'],
    ['Technologies', 'XBI2W2PE'],
    ['Uncategorized', 'XC7TJ6ZH']
  ]),

  /** @constant {Map} tagCategories - Maps ESOVDB video tags' parent categories to their collection keys and their own section parent collection keys in Zotero */
  tagCategories: new Map([
    ['Geology › Geological Time Periods', { 'zoteroKey': 'V5VPX2PQ', 'sectionKey': 'BWD3AUB3' }],
    ['Geology › Geomorphological Features', { 'zoteroKey': 'RMBD6DDR', 'sectionKey': 'BWD3AUB3' }],
    ['Geology › Geological Hazards', { 'zoteroKey': 'UBZ96UU9', 'sectionKey': 'BWD3AUB3' }],
    ['Geology › Igneous & Volcanic Features', { 'zoteroKey': 'YE8GL56Y', 'sectionKey': 'BWD3AUB3' }],
    ['Geology › Geological Structures', { 'zoteroKey': 'TRDKZRVT', 'sectionKey': 'BWD3AUB3' }],
    ['Geology › Impact Events', { 'zoteroKey': 'MVKH36CJ', 'sectionKey': 'BWD3AUB3' }],
    ['Geology › Deep Geological Processes', { 'zoteroKey': '2X3KB9UK', 'sectionKey': 'BWD3AUB3' }],
    ['Geology › Sedimentary Features', { 'zoteroKey': 'HGQBTKQD', 'sectionKey': 'BWD3AUB3' }],
    ['Geology › Geological Events', { 'zoteroKey': 'VEKG4WYC', 'sectionKey': 'BWD3AUB3' }],
    ['Geology › Surface Geological Processes', { 'zoteroKey': 'GHSKYH8D', 'sectionKey': 'BWD3AUB3' }],
    ['Geology › Natural Resources', { 'zoteroKey': 'I57D8EDK', 'sectionKey': 'BWD3AUB3' }],
    ['Geology › Metamorphic Features', { 'zoteroKey': 'GKDBTVRV', 'sectionKey': 'BWD3AUB3' }],
    ['Geology › Misc', { 'zoteroKey': 'IC75AG9A', 'sectionKey': 'BWD3AUB3' }],
    ['Misc › Video Features', { 'zoteroKey': 'AFLTP9UJ', 'sectionKey': 'P57IIL2F' }],
    ['Misc › Cultural Contexts', { 'zoteroKey': 'GHQF6NLX', 'sectionKey': 'P57IIL2F' }],
    ['Misc › Video Genres', { 'zoteroKey': 'M95SG6D4', 'sectionKey': 'P57IIL2F' }],
    ['Misc › Historical Events', { 'zoteroKey': '6AS2M79D', 'sectionKey': 'P57IIL2F' }],
    ['Misc › Other', { 'zoteroKey': 'F8NMHQL8', 'sectionKey': 'P57IIL2F' }],
    ['Petrology › Chemical Elements & Compounds', { 'zoteroKey': 'WEYABF24', 'sectionKey': '93Q83ACC' }],
    ['Petrology › Sediments', { 'zoteroKey': 'Y3JVXAGM', 'sectionKey': '93Q83ACC' }],
    ['Petrology › Metamorphic Rocks', { 'zoteroKey': 'ESLDBDBH', 'sectionKey': '93Q83ACC' }],
    ['Petrology › Igneous Rocks', { 'zoteroKey': 'YMELCFHI', 'sectionKey': '93Q83ACC' }],
    ['Petrology › Sedimentary Rocks', { 'zoteroKey': 'SR38G92F', 'sectionKey': '93Q83ACC' }],
    ['Petrology › Minerals', { 'zoteroKey': 'J6DYKAZU', 'sectionKey': '93Q83ACC' }],
    ['Petrology › Misc', { 'zoteroKey': '3MUQ9BWB', 'sectionKey': '93Q83ACC' }],
    ['Geological Regions › South America', { 'zoteroKey': '2UYF9GDE', 'sectionKey': 'QD48SYT3' }],
    ['Geological Regions › Arctic Ocean', { 'zoteroKey': '76SIR7TN', 'sectionKey': 'QD48SYT3' }],
    ['Geological Regions › Middle East', { 'zoteroKey': 'MKIQPSFD', 'sectionKey': 'QD48SYT3' }],
    ['Geological Regions › Africa', { 'zoteroKey': 'BZ8H97Y4', 'sectionKey': 'QD48SYT3' }],
    ['Geological Regions › Antarctica', { 'zoteroKey': 'A4H8DMCJ', 'sectionKey': 'QD48SYT3' }],
    ['Geological Regions › Indian Ocean', { 'zoteroKey': 'FN2NTICK', 'sectionKey': 'QD48SYT3' }],
    ['Geological Regions › Misc', { 'zoteroKey': 'RCR344TT', 'sectionKey': 'QD48SYT3' }],
    ['Geological Regions › North America', { 'zoteroKey': 'XYTIRFPI', 'sectionKey': 'QD48SYT3' }],
    ['Geological Regions › Asia', { 'zoteroKey': 'KV2D6RI8', 'sectionKey': 'QD48SYT3' }],
    ['Geological Regions › Europe', { 'zoteroKey': 'IPHGQT5Z', 'sectionKey': 'QD48SYT3' }],
    ['Geological Regions › Atlantic Ocean', { 'zoteroKey': '59QYDB7A', 'sectionKey': 'QD48SYT3' }],
    ['Geological Regions › Australasia', { 'zoteroKey': 'EBQ6D8RB', 'sectionKey': 'QD48SYT3' }],
    ['Geological Regions › Pacific Ocean', { 'zoteroKey': 'A9FQFDMP', 'sectionKey': 'QD48SYT3' }],
    ['Geography › Rivers, Lakes, and Terrestrial Water Features', { 'zoteroKey': 'KQIY4I2Q', 'sectionKey': 'KBLIB9IT' }],
    ['Geography › Antarctica', { 'zoteroKey': 'L2KFLJK9', 'sectionKey': 'KBLIB9IT' }],
    ['Geography › Atlantic Ocean', { 'zoteroKey': 'LJ6Z2LH5', 'sectionKey': 'KBLIB9IT' }],
    ['Geography › North America', { 'zoteroKey': 'NIM9XJDP', 'sectionKey': 'KBLIB9IT' }],
    ['Geography › Asia', { 'zoteroKey': '3MNZFELH', 'sectionKey': 'KBLIB9IT' }],
    ['Geography › Australasia', { 'zoteroKey': 'NLFQBNP9', 'sectionKey': 'KBLIB9IT' }],
    ['Geography › Europe', { 'zoteroKey': 'D6LBGDKG', 'sectionKey': 'KBLIB9IT' }],
    ['Geography › Other Oceanic', { 'zoteroKey': '32ZE5D4B', 'sectionKey': 'KBLIB9IT' }],
    ['Geography › Africa', { 'zoteroKey': 'LAFQUF5S', 'sectionKey': 'KBLIB9IT' }],
    ['Geography › Indian Ocean', { 'zoteroKey': 'ZR3WQY9P', 'sectionKey': 'KBLIB9IT' }],
    ['Geography › Pacific Ocean', { 'zoteroKey': 'YXNBY448', 'sectionKey': 'KBLIB9IT' }],
    ['Geography › Arctic Ocean', { 'zoteroKey': 'RLYMUH2H', 'sectionKey': 'KBLIB9IT' }],
    ['Geography › Paleogeography', { 'zoteroKey': 'LXK45IKJ', 'sectionKey': 'KBLIB9IT' }],
    ['Geography › Misc', { 'zoteroKey': 'WDN3XR4J', 'sectionKey': 'KBLIB9IT' }],
    ['Sciences › Misc', { 'zoteroKey': '3GMSUJIY', 'sectionKey': 'NPCFS6M3' }],
    ['Sciences › Petrology', { 'zoteroKey': '3XTGIGVV', 'sectionKey': 'NPCFS6M3' }],
    ['Sciences › Glaciology', { 'zoteroKey': 'JXNR5B6X', 'sectionKey': 'NPCFS6M3' }],
    ['Sciences › Geochronology', { 'zoteroKey': 'AHUGIUIX', 'sectionKey': 'NPCFS6M3' }],
    ['Sciences › Mineralogy', { 'zoteroKey': 'XK6ZZUM7', 'sectionKey': 'NPCFS6M3' }],
    ['Sciences › Geochemistry', { 'zoteroKey': 'FJYJM3DI', 'sectionKey': 'NPCFS6M3' }],
    ['Sciences › Data Science', { 'zoteroKey': 'TSJFSNLM', 'sectionKey': 'NPCFS6M3' }],
    ['Sciences › Origin of Life Sciences', { 'zoteroKey': '3EKY997H', 'sectionKey': 'NPCFS6M3' }],
    ['Sciences › Chemistry', { 'zoteroKey': 'ZD3RMGYZ', 'sectionKey': 'NPCFS6M3' }],
    ['Sciences › Igneous & Metamorphic Petrology', { 'zoteroKey': 'G9JSQQRZ', 'sectionKey': 'NPCFS6M3' }],
    ['Sciences › Economic Geology', { 'zoteroKey': 'A2ZFPAN3', 'sectionKey': 'NPCFS6M3' }],
    ['Sciences › Planetary Science', { 'zoteroKey': '5CIELCLP', 'sectionKey': 'NPCFS6M3' }],
    ['Sciences › Field Geology', { 'zoteroKey': 'JS85BYXK', 'sectionKey': 'NPCFS6M3' }],
    ['Sciences › Biology', { 'zoteroKey': '6F3PYY9U', 'sectionKey': 'NPCFS6M3' }],
    ['Sciences › Geophysics', { 'zoteroKey': 'PMPXZKGZ', 'sectionKey': 'NPCFS6M3' }],
    ['Sciences › Astronomy', { 'zoteroKey': '4X74KAHT', 'sectionKey': 'NPCFS6M3' }],
    ['Sciences › Paleobiology & Paleontology', { 'zoteroKey': '5JCCJ6VI', 'sectionKey': 'NPCFS6M3' }],
    ['Geological Formations › Asia', { 'zoteroKey': '5T3Y45Y5', 'sectionKey': 'S7U6Y3HU' }],
    ['Geological Formations › Antarctica', { 'zoteroKey': 'MI8PE2RH', 'sectionKey': 'S7U6Y3HU' }],
    ['Geological Formations › Australasia', { 'zoteroKey': '2HZCZ4E7', 'sectionKey': 'S7U6Y3HU' }],
    ['Geological Formations › South America', { 'zoteroKey': 'KJ5RCGRV', 'sectionKey': 'S7U6Y3HU' }],
    ['Geological Formations › Misc', { 'zoteroKey': 'U7IZJ8DA', 'sectionKey': 'S7U6Y3HU' }],
    ['Geological Formations › North America', { 'zoteroKey': 'EJABSXMZ', 'sectionKey': 'S7U6Y3HU' }],
    ['Geological Formations › Africa', { 'zoteroKey': 'HDQ99VDD', 'sectionKey': 'S7U6Y3HU' }],
    ['Geological Formations › Europe', { 'zoteroKey': 'YZBJHQH5', 'sectionKey': 'S7U6Y3HU' }],
    ['Geological Formations › Middle East', { 'zoteroKey': 'Z7RCHGZB', 'sectionKey': 'S7U6Y3HU' }],
    ['Ecology › Ecological Regions', { 'zoteroKey': 'JU5MHYTT', 'sectionKey': 'CNUD2XK6' }],
    ['Ecology › Environment', { 'zoteroKey': 'T9YYYJXV', 'sectionKey': 'CNUD2XK6' }],
    ['Ecology › Biological Organisms', { 'zoteroKey': 'CNDNAQNS', 'sectionKey': 'CNUD2XK6' }],
    ['Ecology › Biological Processes', { 'zoteroKey': 'DT6AGGAR', 'sectionKey': 'CNUD2XK6' }],
    ['Ecology › Ecological Features', { 'zoteroKey': 'JU4YD29U', 'sectionKey': 'CNUD2XK6' }],
    ['Ecology › Paleobiological Organisms', { 'zoteroKey': 'RXA6DX8B', 'sectionKey': 'CNUD2XK6' }],
    ['Ecology › Misc', { 'zoteroKey': 'GKYPFW7Q', 'sectionKey': 'CNUD2XK6' }],
    ['Technologies', { 'zoteroKey': 'XBI2W2PE', 'sectionKey': null }],
  // 	['GPlates', { 'zoteroKey': 'IN86S3E4', 'sectionKey': 'XBI2W2PE' }],
  // 	['Clean Energy', { 'zoteroKey': 'AZYZIM2Z', 'sectionKey': 'XBI2W2PE' }],
  // 	['Geo-storage', { 'zoteroKey': 'L3ZG9Y4E', 'sectionKey': 'XBI2W2PE' }],
  // 	['Hydrogen Energy', { 'zoteroKey': '3MISAGP5', 'sectionKey': 'XBI2W2PE' }],
  // 	['Asceptic Drilling', { 'zoteroKey': 'CC4B9WE8', 'sectionKey': 'XBI2W2PE' }],
  // 	['Deep Ocean Drilling', { 'zoteroKey': 'XRI6BZVY', 'sectionKey': 'XBI2W2PE' }],
  // 	['Drillship', { 'zoteroKey': 'V7VF3WFQ', 'sectionKey': 'XBI2W2PE' }]
  ]),

  /** @constant {Map} tags - Maps ESOVDB video tags to their collection keys and parent collection keys in Zotero */
  tags: new Map([
    ['Volcanism', { 'zoteroKey': 'EKCI9SW8', 'categoryKey': 'GHSKYH8D' }],
    ['Washington', { 'zoteroKey': 'D5LD84IH', 'categoryKey': 'NIM9XJDP' }],
    ['Plate Tectonics', { 'zoteroKey': 'B3GPQYFZ', 'categoryKey': '2X3KB9UK' }],
    ['Climate', { 'zoteroKey': 'V66ZIPC8', 'categoryKey': 'T9YYYJXV' }],
    ['Basalt', { 'zoteroKey': '98MM3EUM', 'categoryKey': 'YMELCFHI' }],
    ['Cenozoic', { 'zoteroKey': 'EE2UTJDN', 'categoryKey': 'V5VPX2PQ' }],
    ['Mesozoic', { 'zoteroKey': 'KIBE7NFJ', 'categoryKey': 'V5VPX2PQ' }],
    ['Canada', { 'zoteroKey': 'X4TQJYHT', 'categoryKey': 'NIM9XJDP' }],
    ['Holocene', { 'zoteroKey': 'MY46FT54', 'categoryKey': 'V5VPX2PQ' }],
    ['Hot-spot Volcanism', { 'zoteroKey': 'Q5W4NIW3', 'categoryKey': 'GHSKYH8D' }],
    ['Ice Age Floods', { 'zoteroKey': '7XQ2PZRV', 'categoryKey': 'VEKG4WYC' }],
    ['Mid-ocean Ridge', { 'zoteroKey': 'TFP75ED7', 'categoryKey': 'TRDKZRVT' }],
    ['Orogeny', { 'zoteroKey': 'L2SMMWU3', 'categoryKey': 'GHSKYH8D' }],
    ['Pacific Northwest', { 'zoteroKey': 'VAHIWC6N', 'categoryKey': 'NIM9XJDP' }],
    ['Volcanic Eruption', { 'zoteroKey': 'PZLRPVB6', 'categoryKey': 'GHSKYH8D' }],
    ['Mass Extinctions', { 'zoteroKey': 'PMQDUK59', 'categoryKey': '5JCCJ6VI' }],
    ['Paleoclimatology', { 'zoteroKey': 'T3HFBDD6', 'categoryKey': '3GMSUJIY' }],
    ['Redox Gradient', { 'zoteroKey': 'E6MKRTY6', 'categoryKey': 'FJYJM3DI' }],
    ['Sedimentology', { 'zoteroKey': '2797Z2D6', 'categoryKey': '3GMSUJIY' }],
    ['Serpentinite', { 'zoteroKey': 'FC4MPEIK', 'categoryKey': 'ESLDBDBH' }],
    ['Arctic', { 'zoteroKey': 'ACAL4PZN', 'categoryKey': 'RLYMUH2H' }],
    ['Bacteria', { 'zoteroKey': 'N6FQANSD', 'categoryKey': '6F3PYY9U' }],
    ['Columbia River', { 'zoteroKey': 'TSGQL5PV', 'categoryKey': 'KQIY4I2Q' }],
    ['Columbia River Flood Basalts', { 'zoteroKey': '6VE6386K', 'categoryKey': 'XYTIRFPI' }],
    ['Coulee', { 'zoteroKey': 'LXJABYEW', 'categoryKey': 'RMBD6DDR' }],
    ['Eocene', { 'zoteroKey': 'YDS8A7B2', 'categoryKey': 'V5VPX2PQ' }],
    ['Himalayan Orogeny', { 'zoteroKey': 'GGVZAKKR', 'categoryKey': 'VEKG4WYC' }],
    ['Himalayas', { 'zoteroKey': 'SJEL9S84', 'categoryKey': '3MNZFELH' }],
    ['Iceland', { 'zoteroKey': 'IEBW786G', 'categoryKey': 'D6LBGDKG' }],
    ['Laurentia', { 'zoteroKey': '6Q2X5R5C', 'categoryKey': 'LXK45IKJ' }],
    ['Mediterranean Sea', { 'zoteroKey': 'KZ95X4ZJ', 'categoryKey': '32ZE5D4B' }],
    ['Pleistocene', { 'zoteroKey': 'BYPSGPG2', 'categoryKey': 'V5VPX2PQ' }],
    ['Seafloor Spreading', { 'zoteroKey': 'P7GCF8YG', 'categoryKey': '2X3KB9UK' }],
    ['Serpentinization', { 'zoteroKey': 'HMV7MB85', 'categoryKey': '2X3KB9UK' }],
    ['Subduction', { 'zoteroKey': 'WE6AAX5Y', 'categoryKey': '2X3KB9UK' }],
    ['Archea', { 'zoteroKey': 'RG3C6H6L', 'categoryKey': '6F3PYY9U' }],
    ['Archean', { 'zoteroKey': 'N5G4PG26', 'categoryKey': 'V5VPX2PQ' }],
    ['Banded Iron Formations (BIFs)', { 'zoteroKey': 'D8HXKJJJ', 'categoryKey': 'SR38G92F' }],
    ['British Columbia', { 'zoteroKey': '7WTQX4LT', 'categoryKey': 'NIM9XJDP' }],
    ['Cascades', { 'zoteroKey': 'ZLX7EFN5', 'categoryKey': 'NIM9XJDP' }],
    ['Exhumation', { 'zoteroKey': 'DJL3Y8R9', 'categoryKey': '2X3KB9UK' }],
    ['Fagradalsfjall Volcano', { 'zoteroKey': 'ZUE9HJEP', 'categoryKey': 'IPHGQT5Z' }],
    ['Flood Basalts', { 'zoteroKey': '8SAPKLG5', 'categoryKey': 'GHSKYH8D' }],
    ['Geochronology', { 'zoteroKey': 'P3KQ2BVF', 'categoryKey': 'AHUGIUIX' }],
    ['Geodynamics', { 'zoteroKey': 'FXTVHCCA', 'categoryKey': 'PMPXZKGZ' }],
    ['Geology', { 'zoteroKey': 'LX6VQ2RB', 'categoryKey': '3GMSUJIY' }],
    ['Geomorphology', { 'zoteroKey': 'EFPAAMPC', 'categoryKey': 'RMBD6DDR' }],
    ['Glaciation', { 'zoteroKey': '8HDR48ZH', 'categoryKey': 'T9YYYJXV' }],
    ['Great Oxidation Event (GOE)', { 'zoteroKey': 'QBE24YBN', 'categoryKey': 'VEKG4WYC' }],
    ['History', { 'zoteroKey': '5DWIKRP2', 'categoryKey': 'M95SG6D4' }],
    ['Hydrothermal Vent', { 'zoteroKey': '9MXKIYFB', 'categoryKey': 'YE8GL56Y' }],
    ['Idaho', { 'zoteroKey': 'R8LTCJWY', 'categoryKey': 'NIM9XJDP' }],
    ['Landslides', { 'zoteroKey': '99UFPBXD', 'categoryKey': 'UBZ96UU9' }],
    ['Large Igneous Provinces (LIPs)', { 'zoteroKey': '6U6NWVBZ', 'categoryKey': 'RMBD6DDR' }],
    ['Metamorphic Petrology', { 'zoteroKey': '5WPNH5VJ', 'categoryKey': '3GMSUJIY' }],
    ['Native American', { 'zoteroKey': 'BH5SECUS', 'categoryKey': 'GHQF6NLX' }],
    ['Origin of Life', { 'zoteroKey': 'U4YHV7Q2', 'categoryKey': '5JCCJ6VI' }],
    ['Paleocene-Eocene Thermal Maximum (PETM)', { 'zoteroKey': 'LQJZWF5N', 'categoryKey': 'VEKG4WYC' }],
    ['Paleomagnetism', { 'zoteroKey': '56FAVWX7', 'categoryKey': 'PMPXZKGZ' }],
    ['Proterozoic', { 'zoteroKey': 'ZZ7W6M75', 'categoryKey': 'V5VPX2PQ' }],
    ['Regional Metamorphism', { 'zoteroKey': 'ZRX3H33X', 'categoryKey': '2X3KB9UK' }],
    ['Tibet', { 'zoteroKey': 'U6KT9Q78', 'categoryKey': '3MNZFELH' }],
    ['Tibetan Plateau', { 'zoteroKey': 'MPGVCVFH', 'categoryKey': '3MNZFELH' }],
    ['Triassic', { 'zoteroKey': 'KSRPX29X', 'categoryKey': 'V5VPX2PQ' }],
    ['Alaska', { 'zoteroKey': 'CL4AX4VG', 'categoryKey': 'NIM9XJDP' }],
    ['Basins', { 'zoteroKey': '6WDIKWM8', 'categoryKey': 'RMBD6DDR' }],
    ['Biogeochemistry', { 'zoteroKey': 'XPCTM2E5', 'categoryKey': 'FJYJM3DI' }],
    ['Biomineralization', { 'zoteroKey': 'UWPMMG2X', 'categoryKey': 'DT6AGGAR' }],
    ['Biosphere', { 'zoteroKey': 'AFBBBDHK', 'categoryKey': 'T9YYYJXV' }],
    ['Blueschist', { 'zoteroKey': 'IBWVEWWH', 'categoryKey': 'ESLDBDBH' }],
    ['British Isles', { 'zoteroKey': 'ZU52B7TW', 'categoryKey': 'D6LBGDKG' }],
    ['Caldera', { 'zoteroKey': '6DYVZUJI', 'categoryKey': 'YE8GL56Y' }],
    ['Carbon', { 'zoteroKey': 'HA8VHB47', 'categoryKey': 'WEYABF24' }],
    ['Carbon Cycle', { 'zoteroKey': 'YDZPIH2F', 'categoryKey': 'T9YYYJXV' }],
    ['Carbonate', { 'zoteroKey': 'XNJELGN8', 'categoryKey': 'SR38G92F' }],
    ['Carnian Pluvial Episode', { 'zoteroKey': 'ZGZWYNZ2', 'categoryKey': 'VEKG4WYC' }],
    ['Co-evolution of the Geo- and Biospheres', { 'zoteroKey': 'LD8CYRZ7', 'categoryKey': '3EKY997H' }],
    ['Copper', { 'zoteroKey': 'BVMGUFXM', 'categoryKey': 'A2ZFPAN3' }],
    ['Cryogenian', { 'zoteroKey': 'XD39NZW4', 'categoryKey': 'V5VPX2PQ' }],
    ['Deccan Flood Basalts', { 'zoteroKey': 'H5K9QHDK', 'categoryKey': 'VEKG4WYC' }],
    ['Drowned Forest', { 'zoteroKey': 'YJEPZISI', 'categoryKey': 'JU4YD29U' }],
    ['Ediacaran', { 'zoteroKey': 'CS4VASVL', 'categoryKey': 'V5VPX2PQ' }],
    ['Geobiology', { 'zoteroKey': 'JS25HSTI', 'categoryKey': '6F3PYY9U' }],
    ['Geosphere', { 'zoteroKey': 'NW4JZEUW', 'categoryKey': 'T9YYYJXV' }],
    ['Glaciology', { 'zoteroKey': 'GIGDEN7J', 'categoryKey': 'JS85BYXK' }],
    ['Granite', { 'zoteroKey': 'XSZ77ZH6', 'categoryKey': 'YMELCFHI' }],
    ['Headscarp', { 'zoteroKey': 'J7YTVHZC', 'categoryKey': 'RMBD6DDR' }],
    ['High-pressure Low-temperature Metamorphism', { 'zoteroKey': '6WS5B7BL', 'categoryKey': '2X3KB9UK' }],
    ['Hydrosphere / Water Cycle', { 'zoteroKey': '5F8DPCPS', 'categoryKey': 'T9YYYJXV' }],
    ['Hydrothermal Alteration', { 'zoteroKey': 'E687TJ93', 'categoryKey': 'GHSKYH8D' }],
    ['Ignimbrites', { 'zoteroKey': '4ZPLBSQR', 'categoryKey': 'YE8GL56Y' }],
    ['Impact Events', { 'zoteroKey': 'NEFSPNBH', 'categoryKey': 'GHSKYH8D' }],
    ['Intracontinental Rifting', { 'zoteroKey': 'VZHBSB5M', 'categoryKey': '2X3KB9UK' }],
    ['Iron', { 'zoteroKey': 'KYX4S7W3', 'categoryKey': 'WEYABF24' }],
    ['Landslide Lake', { 'zoteroKey': '45F3GQIW', 'categoryKey': 'RMBD6DDR' }],
    ['Landslide Lake Outburst Flood', { 'zoteroKey': '63CLHMUX', 'categoryKey': 'UBZ96UU9' }],
    ['Limestone', { 'zoteroKey': '26GCA564', 'categoryKey': 'SR38G92F' }],
    ['Lost City Hydrothermal Field', { 'zoteroKey': 'ZVIABA9S', 'categoryKey': '32ZE5D4B' }],
    ['Marine', { 'zoteroKey': 'QX2ILRTI', 'categoryKey': 'RMBD6DDR' }],
    ['Mendeleev Ridge', { 'zoteroKey': 'ASU9DT9J', 'categoryKey': '32ZE5D4B' }],
    ['Mesoproterozoic', { 'zoteroKey': 'LJ3MC8T7', 'categoryKey': 'V5VPX2PQ' }],
    ['Metabolism', { 'zoteroKey': 'FN6FXBC6', 'categoryKey': '6F3PYY9U' }],
    ['Metamorphic Rock', { 'zoteroKey': 'PRAVA8TP', 'categoryKey': 'ESLDBDBH' }],
    ['Mid-Tertiary Ignimbrite Flare-up', { 'zoteroKey': '333NVQVC', 'categoryKey': 'VEKG4WYC' }],
    ['Minerals', { 'zoteroKey': 'P9ACF5MC', 'categoryKey': 'J6DYKAZU' }],
    ['Monsoon', { 'zoteroKey': 'S3NCRGYJ', 'categoryKey': 'T9YYYJXV' }],
    ['Neoproterozoic', { 'zoteroKey': '248Y9JB8', 'categoryKey': 'V5VPX2PQ' }],
    ['North America', { 'zoteroKey': 'SUMI466K', 'categoryKey': 'NIM9XJDP' }],
    ['Ophiolite', { 'zoteroKey': 'E574C8ZA', 'categoryKey': 'TRDKZRVT' }],
    ['Ore Deposition', { 'zoteroKey': 'MNHRWZEE', 'categoryKey': 'GHSKYH8D' }],
    ['Oregon', { 'zoteroKey': '25Z73NHA', 'categoryKey': 'NIM9XJDP' }],
    ['Paleocene', { 'zoteroKey': '26PWYLRH', 'categoryKey': 'V5VPX2PQ' }],
    ['Paleogeography', { 'zoteroKey': 'R7P2LD36', 'categoryKey': '3GMSUJIY' }],
    ['Paleozoic', { 'zoteroKey': 'J75Q2GQW', 'categoryKey': 'V5VPX2PQ' }],
    ['Peridotite', { 'zoteroKey': '3C2334FQ', 'categoryKey': 'YMELCFHI' }],
    ['Pliocene', { 'zoteroKey': '3U76HW4M', 'categoryKey': 'V5VPX2PQ' }],
    ['Porphyry Copper', { 'zoteroKey': 'NI3EPKPK', 'categoryKey': 'A2ZFPAN3' }],
    ['Porphyry Ore Deposits', { 'zoteroKey': 'KNSKH6U9', 'categoryKey': 'A2ZFPAN3' }],
    ['Rift Zone', { 'zoteroKey': 'YF4LHYZW', 'categoryKey': 'RMBD6DDR' }],
    ['River', { 'zoteroKey': 'U5HKWZRB', 'categoryKey': 'RMBD6DDR' }],
    ['Scotland', { 'zoteroKey': '8T68TKJG', 'categoryKey': 'D6LBGDKG' }],
    ['Sediment', { 'zoteroKey': 'C3DFC9TN', 'categoryKey': 'GHSKYH8D' }],
    ['Sediment Transport', { 'zoteroKey': 'JC8KL5VJ', 'categoryKey': 'GHSKYH8D' }],
    ['Serpentine', { 'zoteroKey': 'U768UJXA', 'categoryKey': 'J6DYKAZU' }],
    ['Shield Volcano', { 'zoteroKey': 'TAANBHEW', 'categoryKey': 'YE8GL56Y' }],
    ['Slab Break-off', { 'zoteroKey': 'V8D5EJ6Q', 'categoryKey': '2X3KB9UK' }],
    ['Snake River Plain', { 'zoteroKey': 'B4I9E648', 'categoryKey': 'NIM9XJDP' }],
    ['Spatter Cone', { 'zoteroKey': 'ZTTUZ6DK', 'categoryKey': 'YE8GL56Y' }],
    ['Supercontinent Cycle', { 'zoteroKey': 'EV4DFWQT', 'categoryKey': '2X3KB9UK' }],
    ['Supervolcano', { 'zoteroKey': 'N56VHSSW', 'categoryKey': 'RMBD6DDR' }],
    ['Teton Range', { 'zoteroKey': 'RL9LR25K', 'categoryKey': 'NIM9XJDP' }],
    ['Travel', { 'zoteroKey': 'RUBPKQDG', 'categoryKey': 'M95SG6D4' }],
    ['U-Pb Isotope Geochronology', { 'zoteroKey': 'HKEWIUK7', 'categoryKey': 'FJYJM3DI' }],
    ['Wyoming', { 'zoteroKey': 'PWUE26RM', 'categoryKey': 'NIM9XJDP' }],
    ['Younger Dryas', { 'zoteroKey': '7ZJDS4RB', 'categoryKey': 'VEKG4WYC' }],
    ['Accomodation Space', { 'zoteroKey': 'A9TMCFZV', 'categoryKey': 'RMBD6DDR' }],
    ['Accretionary Model of Planet Formation', { 'zoteroKey': 'RRB2Y4VS', 'categoryKey': '5CIELCLP' }],
    ['Accretionary Orogen', { 'zoteroKey': 'SFQCIV9N', 'categoryKey': 'GHSKYH8D' }],
    ['Accretionary Wedge', { 'zoteroKey': 'WBJXGW2R', 'categoryKey': 'TRDKZRVT' }],
    ['Accumulation Zone', { 'zoteroKey': '2SMJAFSL', 'categoryKey': 'JXNR5B6X' }],
    ['Adriatic Plate', { 'zoteroKey': 'MJ79YCB2', 'categoryKey': 'IPHGQT5Z' }],
    ['Africa', { 'zoteroKey': 'S8BRZQQC', 'categoryKey': 'LAFQUF5S' }],
    ['Alpha Ridge', { 'zoteroKey': 'QAWW65FC', 'categoryKey': '32ZE5D4B' }],
    ['Alpine Orogeny', { 'zoteroKey': 'K8BQZP3Z', 'categoryKey': 'VEKG4WYC' }],
    ['Anaerobic Respiration', { 'zoteroKey': 'GEY2XS2U', 'categoryKey': 'DT6AGGAR' }],
    ['Apparent Polar Wander (APW)', { 'zoteroKey': 'SFV4EUDR', 'categoryKey': '2X3KB9UK' }],
    ['Arabian-Nubian Shield', { 'zoteroKey': 'EEYURPIK', 'categoryKey': 'BZ8H97Y4' }],
    ['Aragonite', { 'zoteroKey': 'W3QA56E2', 'categoryKey': 'J6DYKAZU' }],
    ['Asceptic Drilling', { 'zoteroKey': 'CC4B9WE8', 'categoryKey': 'XBI2W2PE' }],
    ['Ash-fall Tuff', { 'zoteroKey': 'CEISIA2M', 'categoryKey': 'YE8GL56Y' }],
    ['Ash-flow Tuff', { 'zoteroKey': 'A9ZTTYGM', 'categoryKey': 'YMELCFHI' }],
    ['Astrobiology', { 'zoteroKey': 'JVCKVU5M', 'categoryKey': '6F3PYY9U' }],
    ['Avalonia', { 'zoteroKey': 'R2HT5MNS', 'categoryKey': 'LXK45IKJ' }],
    ['Back-arc Basins', { 'zoteroKey': 'LLPMS46H', 'categoryKey': 'RMBD6DDR' }],
    ['Basaltic Plains Volcanism', { 'zoteroKey': '6QSFF5YY', 'categoryKey': 'GHSKYH8D' }],
    ['Basanite', { 'zoteroKey': 'H9YMN4DB', 'categoryKey': 'YMELCFHI' }],
    ['Batholith', { 'zoteroKey': 'CTHKKKW4', 'categoryKey': 'YE8GL56Y' }],
    ['Bayan Obo Complex', { 'zoteroKey': '3NY7A5DI', 'categoryKey': 'HDQ99VDD' }],
    ['Biogenic Sediments', { 'zoteroKey': '349DFS3P', 'categoryKey': 'SR38G92F' }],
    ['Boring Billion', { 'zoteroKey': 'HTMYRJL5', 'categoryKey': 'VEKG4WYC' }],
    ['Bowen\'s Reaction Series', { 'zoteroKey': 'LKM3UMQB', 'categoryKey': 'G9JSQQRZ' }],
    ['Brandberg Complex', { 'zoteroKey': '5BQT2F2H', 'categoryKey': 'HDQ99VDD' }],
    ['Breakup of Pangea', { 'zoteroKey': '8FTZTABL', 'categoryKey': 'VEKG4WYC' }],
    ['Bresse Graben', { 'zoteroKey': 'HA2H8T8R', 'categoryKey': 'IPHGQT5Z' }],
    ['Brittle Deformation', { 'zoteroKey': 'ZKJ7QU4Q', 'categoryKey': 'GHSKYH8D' }],
    ['Calabrian Arc', { 'zoteroKey': 'IPLMT9QS', 'categoryKey': 'IPHGQT5Z' }],
    ['Calcite', { 'zoteroKey': 'T7HG729H', 'categoryKey': 'J6DYKAZU' }],
    ['California', { 'zoteroKey': 'A7FTFMTZ', 'categoryKey': 'NIM9XJDP' }],
    ['Campi Flegrei/Phlegrean Fields', { 'zoteroKey': 'K7GLL6RT', 'categoryKey': 'D6LBGDKG' }],
    ['Canadian Shield', { 'zoteroKey': 'ACG9NVVT', 'categoryKey': 'XYTIRFPI' }],
    ['Canary Islands', { 'zoteroKey': 'YRP5M6ZE', 'categoryKey': 'D6LBGDKG' }],
    ['Carbon Isotope Geochemistry', { 'zoteroKey': 'RUVJ94MV', 'categoryKey': 'FJYJM3DI' }],
    ['Cascades Arc', { 'zoteroKey': '8JGHC6YY', 'categoryKey': 'XYTIRFPI' }],
    ['Channel Flow', { 'zoteroKey': 'L6KAJCJD', 'categoryKey': '2X3KB9UK' }],
    ['Chelan Migmatite Complex', { 'zoteroKey': 'BAPQ49J7', 'categoryKey': 'EJABSXMZ' }],
    ['Chemistry', { 'zoteroKey': 'Z9GTABLT', 'categoryKey': '3GMSUJIY' }],
    ['Chemoautotrophy', { 'zoteroKey': 'WDELGY7D', 'categoryKey': 'DT6AGGAR' }],
    ['Chemolithotrophy', { 'zoteroKey': 'RKPHBYTZ', 'categoryKey': 'DT6AGGAR' }],
    ['Chert', { 'zoteroKey': 'FPRXGHVP', 'categoryKey': 'SR38G92F' }],
    ['Chicxulub Impact Event', { 'zoteroKey': 'YKBT4N89', 'categoryKey': 'VEKG4WYC' }],
    ['Chromite', { 'zoteroKey': 'Q9C7332B', 'categoryKey': 'J6DYKAZU' }],
    ['Chromium', { 'zoteroKey': 'E8RJ6A63', 'categoryKey': 'WEYABF24' }],
    ['Chronostratigraphy', { 'zoteroKey': '63STQ72D', 'categoryKey': 'AHUGIUIX' }],
    ['Chumstick Formation', { 'zoteroKey': 'NAXD8L9S', 'categoryKey': 'EJABSXMZ' }],
    ['Clastic Dikes', { 'zoteroKey': 'D2KWQTPB', 'categoryKey': 'HGQBTKQD' }],
    ['Clay Minerals', { 'zoteroKey': 'WHJZ5C4Q', 'categoryKey': 'J6DYKAZU' }],
    ['Clean Energy', { 'zoteroKey': 'AZYZIM2Z', 'categoryKey': 'XBI2W2PE' }],
    ['Climate Change', { 'zoteroKey': '7MQ4UFAR', 'categoryKey': 'T9YYYJXV' }],
    ['Coast Mountains', { 'zoteroKey': 'FZ8KJLMM', 'categoryKey': 'NIM9XJDP' }],
    ['Coastal Processes', { 'zoteroKey': 'SK6VAZHT', 'categoryKey': 'GHSKYH8D' }],
    ['Continental Collision', { 'zoteroKey': 'APDFDJC2', 'categoryKey': 'GHSKYH8D' }],
    ['Convergent Margin', { 'zoteroKey': 'HRC9HT8M', 'categoryKey': 'RMBD6DDR' }],
    ['Coppermine River', { 'zoteroKey': '657BGH44', 'categoryKey': 'KQIY4I2Q' }],
    ['Coronal Mass Ejection (CME)', { 'zoteroKey': 'GA8GDZL5', 'categoryKey': '4X74KAHT' }],
    ['Cratons', { 'zoteroKey': 'B43VEZ9L', 'categoryKey': 'RMBD6DDR' }],
    ['Cretaceous', { 'zoteroKey': '8WAC9GHR', 'categoryKey': 'V5VPX2PQ' }],
    ['Cretaceous Superchron', { 'zoteroKey': 'NC8DHWDM', 'categoryKey': 'VEKG4WYC' }],
    ['Cretaceous Superplume Event', { 'zoteroKey': '9WFTTSV9', 'categoryKey': 'VEKG4WYC' }],
    ['Critical Wedge Theory', { 'zoteroKey': '99HQ87YA', 'categoryKey': 'GHSKYH8D' }],
    ['Cross-polarized Light', { 'zoteroKey': 'QJN5NLWR', 'categoryKey': 'XK6ZZUM7' }],
    ['Cumbre Vieja Rift Zone', { 'zoteroKey': 'ZCMFFBKC', 'categoryKey': 'IPHGQT5Z' }],
    ['Cyanobacteria', { 'zoteroKey': '6VX4KMJL', 'categoryKey': '6F3PYY9U' }],
    ['Database', { 'zoteroKey': '6ILGI5PR', 'categoryKey': 'TSJFSNLM' }],
    ['Dead Sea', { 'zoteroKey': 'BPMM73UB', 'categoryKey': 'KQIY4I2Q' }],
    ['Dead Sea Fault', { 'zoteroKey': '26G4Q6LF', 'categoryKey': 'TRDKZRVT' }],
    ['Debris Flow', { 'zoteroKey': 'GCQ7UTDE', 'categoryKey': 'UBZ96UU9' }],
    ['Decompression Melting', { 'zoteroKey': 'FMXBBWS3', 'categoryKey': '2X3KB9UK' }],
    ['Deep Ocean Drilling', { 'zoteroKey': 'XRI6BZVY', 'categoryKey': 'XBI2W2PE' }],
    ['Deep Subsurface Biosphere', { 'zoteroKey': 'MSWS2HP9', 'categoryKey': 'JU5MHYTT' }],
    ['Dehydration', { 'zoteroKey': 'QPDLR3WN', 'categoryKey': 'ZD3RMGYZ' }],
    ['Deltas', { 'zoteroKey': '2IKJ8TWP', 'categoryKey': 'RMBD6DDR' }],
    ['Depositional Environments', { 'zoteroKey': 'MW7CCXZT', 'categoryKey': 'RMBD6DDR' }],
    ['Diagenesis', { 'zoteroKey': 'HUD2TEQ3', 'categoryKey': 'GHSKYH8D' }],
    ['Diffusion Creep', { 'zoteroKey': '2B9NBS6W', 'categoryKey': '2X3KB9UK' }],
    ['Dislocation Creep', { 'zoteroKey': 'F676M9W9', 'categoryKey': '2X3KB9UK' }],
    ['Dolomite', { 'zoteroKey': '73BC3VLV', 'categoryKey': '2X3KB9UK' }],
    ['Drillship', { 'zoteroKey': 'V7VF3WFQ', 'categoryKey': 'XBI2W2PE' }],
    ['Ductile Deformation', { 'zoteroKey': 'EN652FKE', 'categoryKey': '2X3KB9UK' }],
    ['Dunite', { 'zoteroKey': 'M9PDZRTE', 'categoryKey': 'YMELCFHI' }],
    ['Dynamic Topography', { 'zoteroKey': 'Q3M5EUK9', 'categoryKey': '2X3KB9UK' }],
    ['East Africa Orogen', { 'zoteroKey': 'WBNQ4CWR', 'categoryKey': 'VEKG4WYC' }],
    ['East African Rift', { 'zoteroKey': '6YMZ4765', 'categoryKey': 'BZ8H97Y4' }],
    ['Easton Metamorphic Suite', { 'zoteroKey': 'UPX5TBPG', 'categoryKey': 'EJABSXMZ' }],
    ['Eclogite', { 'zoteroKey': 'PA32LSXK', 'categoryKey': 'ESLDBDBH' }],
    ['Ejecta Blanket', { 'zoteroKey': '22L5WXNM', 'categoryKey': 'MVKH36CJ' }],
    ['Eldfell', { 'zoteroKey': 'TLKXGGRM', 'categoryKey': 'IPHGQT5Z' }],
    ['Electrolysis', { 'zoteroKey': 'LS3FD7PE', 'categoryKey': 'ZD3RMGYZ' }],
    ['England', { 'zoteroKey': 'YCJ95IMF', 'categoryKey': 'D6LBGDKG' }],
    ['Epidote', { 'zoteroKey': 'VZFDN4UN', 'categoryKey': 'J6DYKAZU' }],
    ['Eratosthenes Seamount', { 'zoteroKey': 'Q38N48UY', 'categoryKey': 'YXNBY448' }],
    ['Erosion', { 'zoteroKey': 'WIM75AJV', 'categoryKey': 'GHSKYH8D' }],
    ['European Cenozoic Rift System', { 'zoteroKey': 'RMQH9JYR', 'categoryKey': 'IPHGQT5Z' }],
    ['Evolution', { 'zoteroKey': 'B6G5DKKS', 'categoryKey': '5JCCJ6VI' }],
    ['Extension', { 'zoteroKey': 'BGASS477', 'categoryKey': '2X3KB9UK' }],
    ['Extraterrestrial Life', { 'zoteroKey': 'AK8IZZGQ', 'categoryKey': '5CIELCLP' }],
    ['Fissure Volcano', { 'zoteroKey': 'IHJKLFAJ', 'categoryKey': 'YE8GL56Y' }],
    ['Flux Melting', { 'zoteroKey': 'CWPNDX3J', 'categoryKey': '2X3KB9UK' }],
    ['Fold', { 'zoteroKey': 'KDG4PN5W', 'categoryKey': 'TRDKZRVT' }],
    ['Foraminifera', { 'zoteroKey': 'UWRAU2AZ', 'categoryKey': '6F3PYY9U' }],
    ['Formation of the Planet', { 'zoteroKey': 'VUZ44PDW', 'categoryKey': '5CIELCLP' }],
    ['Fossils', { 'zoteroKey': '7XUFP5HN', 'categoryKey': '5JCCJ6VI' }],
    ['Fracture Zone', { 'zoteroKey': 'NZ7WASTI', 'categoryKey': 'TRDKZRVT' }],
    ['Full-plate Tectonic Model', { 'zoteroKey': 'ZQBX7F6J', 'categoryKey': 'PMPXZKGZ' }],
    ['Fumaroles', { 'zoteroKey': 'T6GNRX9Z', 'categoryKey': 'YE8GL56Y' }],
    ['Gakkel Ridge', { 'zoteroKey': 'E84CBWDU', 'categoryKey': '32ZE5D4B' }],
    ['Galena', { 'zoteroKey': 'E5PHNIGH', 'categoryKey': 'J6DYKAZU' }],
    ['Gallionella ferruginea', { 'zoteroKey': 'HVV79QTQ', 'categoryKey': 'CNDNAQNS' }],
    ['Garnet', { 'zoteroKey': 'P8KBJ8BD', 'categoryKey': 'J6DYKAZU' }],
    ['Geo-storage', { 'zoteroKey': 'L3ZG9Y4E', 'categoryKey': 'XBI2W2PE' }],
    ['Geology 101', { 'zoteroKey': 'BSWWY5ER', 'categoryKey': 'M95SG6D4' }],
    ['Geothermal Gradient', { 'zoteroKey': 'CFDNJDRV', 'categoryKey': 'PMPXZKGZ' }],
    ['Glacial Lake', { 'zoteroKey': 'WR3A2HHA', 'categoryKey': 'RMBD6DDR' }],
    ['Glacier', { 'zoteroKey': 'EGNZIN8J', 'categoryKey': 'RMBD6DDR' }],
    ['Glacier Retreat', { 'zoteroKey': 'MEN56VWE', 'categoryKey': 'JXNR5B6X' }],
    ['Gneiss', { 'zoteroKey': 'S4PCUSK7', 'categoryKey': 'ESLDBDBH' }],
    ['GPlates', { 'zoteroKey': 'IN86S3E4', 'categoryKey': 'XBI2W2PE' }],
    ['Grain-boundary Sliding', { 'zoteroKey': 'JNF6RLU6', 'categoryKey': '2X3KB9UK' }],
    ['Greenschist', { 'zoteroKey': 'USRSYS4V', 'categoryKey': 'ESLDBDBH' }],
    ['Greenstone', { 'zoteroKey': 'QLJAE6QU', 'categoryKey': 'ESLDBDBH' }],
    ['Groundwater', { 'zoteroKey': 'CVZ8KP8B', 'categoryKey': 'T9YYYJXV' }],
    ['Halite', { 'zoteroKey': 'K6J4DFFA', 'categoryKey': 'J6DYKAZU' }],
    ['Harzburgite', { 'zoteroKey': '59BX67XH', 'categoryKey': 'YMELCFHI' }],
    ['Hawaii', { 'zoteroKey': 'S7CEUKU2', 'categoryKey': 'YXNBY448' }],
    ['Heimaey', { 'zoteroKey': '995RRSBQ', 'categoryKey': 'D6LBGDKG' }],
    ['Hike', { 'zoteroKey': 'N3LCITQZ', 'categoryKey': 'M95SG6D4' }],
    ['Hyaloclastite', { 'zoteroKey': 'MM5HZEJ5', 'categoryKey': 'YMELCFHI' }],
    ['Hydrocarbon Exploration', { 'zoteroKey': 'NNPMRMIB', 'categoryKey': 'A2ZFPAN3' }],
    ['Hydrogen Energy', { 'zoteroKey': '3MISAGP5', 'categoryKey': 'XBI2W2PE' }],
    ['Hydrology', { 'zoteroKey': 'I5DSACLN', 'categoryKey': '3GMSUJIY' }],
    ['Ice Age', { 'zoteroKey': 'KKVPR3RJ', 'categoryKey': 'VEKG4WYC' }],
    ['Igneous Rock', { 'zoteroKey': 'Q9P6PMBM', 'categoryKey': 'YMELCFHI' }],
    ['Impact Breccia', { 'zoteroKey': 'HKWMYTM6', 'categoryKey': 'MVKH36CJ' }],
    ['Intraplate Volcanism', { 'zoteroKey': '4DJKHM8Y', 'categoryKey': '2X3KB9UK' }],
    ['Ionosphere', { 'zoteroKey': 'JXGIDC6U', 'categoryKey': 'T9YYYJXV' }],
    ['Iron Bacteria', { 'zoteroKey': 'JI34DMSA', 'categoryKey': 'CNDNAQNS' }],
    ['Iron Ore', { 'zoteroKey': 'EW3EDM9I', 'categoryKey': 'I57D8EDK' }],
    ['Iron-oxidizing Bacteria (FeOB)', { 'zoteroKey': 'J4B9U7EE', 'categoryKey': 'CNDNAQNS' }],
    ['Island Arc', { 'zoteroKey': 'P7MLWYEQ', 'categoryKey': 'TRDKZRVT' }],
    ['Jade', { 'zoteroKey': 'AUG3882R', 'categoryKey': 'ESLDBDBH' }],
    ['Jadeite', { 'zoteroKey': '2H2MYK22', 'categoryKey': 'J6DYKAZU' }],
    ['Jadeitite', { 'zoteroKey': 'ML298RA7', 'categoryKey': 'ESLDBDBH' }],
    ['Juan de Fuca Plate', { 'zoteroKey': 'HD9L9F58', 'categoryKey': 'A9FQFDMP' }],
    ['Jurassic', { 'zoteroKey': '3Z939QWI', 'categoryKey': 'V5VPX2PQ' }],
    ['K-Pg Boundary', { 'zoteroKey': 'H94LUM6N', 'categoryKey': 'V5VPX2PQ' }],
    ['Karoo Basin', { 'zoteroKey': 'AMLA2ZLJ', 'categoryKey': 'BZ8H97Y4' }],
    ['Karoo Large Igneous Province', { 'zoteroKey': '3HZ94QWH', 'categoryKey': 'BZ8H97Y4' }],
    ['Kīlauea', { 'zoteroKey': 'BW9SKWXV', 'categoryKey': 'A9FQFDMP' }],
    ['Kimberlites', { 'zoteroKey': '3CXYE26F', 'categoryKey': 'A2ZFPAN3' }],
    ['Krebs Cycle', { 'zoteroKey': 'FY6ACBNT', 'categoryKey': '6F3PYY9U' }],
    ['La Palma', { 'zoteroKey': '3F4MUGLU', 'categoryKey': 'D6LBGDKG' }],
    ['LA-ICP-MS', { 'zoteroKey': 'FFRJASIE', 'categoryKey': 'FJYJM3DI' }],
    ['Lac de Gras', { 'zoteroKey': 'HQPLNLTH', 'categoryKey': 'KQIY4I2Q' }],
    ['Lahar', { 'zoteroKey': 'YLZT673F', 'categoryKey': 'UBZ96UU9' }],
    ['Lake Superior', { 'zoteroKey': 'L8XUG2AY', 'categoryKey': 'NIM9XJDP' }],
    ['Lakes', { 'zoteroKey': 'UP9A5SKH', 'categoryKey': 'RMBD6DDR' }],
    ['Lava Diversion', { 'zoteroKey': 'EZWMER9J', 'categoryKey': 'UBZ96UU9' }],
    ['Layered Igneous Intrusion', { 'zoteroKey': 'M8YWIBUN', 'categoryKey': 'TRDKZRVT' }],
    ['Levant Margin', { 'zoteroKey': 'KX9BUS7D', 'categoryKey': 'MKIQPSFD' }],
    ['Lherzolite', { 'zoteroKey': 'W5AG2ART', 'categoryKey': 'YMELCFHI' }],
    ['Limnology', { 'zoteroKey': '544M55FE', 'categoryKey': '3GMSUJIY' }],
    ['Lithospheric Delamination', { 'zoteroKey': 'WLJALCKS', 'categoryKey': '2X3KB9UK' }],
    ['LLSVP', { 'zoteroKey': 'ABPTMTVP', 'categoryKey': '2X3KB9UK' }],
    ['Loess', { 'zoteroKey': 'JRKW6HSD', 'categoryKey': 'Y3JVXAGM' }],
    ['Lomonosov Ridge', { 'zoteroKey': 'XWY7BQ4H', 'categoryKey': '32ZE5D4B' }],
    ['Machine Learning', { 'zoteroKey': 'RVPC66GP', 'categoryKey': 'TSJFSNLM' }],
    ['Mafic', { 'zoteroKey': '2ENPLS2L', 'categoryKey': 'G9JSQQRZ' }],
    ['Magnesium', { 'zoteroKey': 'DKMGRC2I', 'categoryKey': 'WEYABF24' }],
    ['Magnetostratigraphy', { 'zoteroKey': 'VVJC8TRW', 'categoryKey': 'PMPXZKGZ' }],
    ['Mantle Wedge', { 'zoteroKey': 'EWBKTVCL', 'categoryKey': 'TRDKZRVT' }],
    ['Marine Terraces', { 'zoteroKey': 'KWKMSZGG', 'categoryKey': 'RMBD6DDR' }],
    ['Mariprofundus ferrooxydans', { 'zoteroKey': '53T27XAC', 'categoryKey': 'CNDNAQNS' }],
    ['Mars', { 'zoteroKey': '8BLD4AVI', 'categoryKey': '5CIELCLP' }],
    ['Mass Wasting', { 'zoteroKey': 'E8HBFTKW', 'categoryKey': 'GHSKYH8D' }],
    ['Meltwater', { 'zoteroKey': 'LV3R5ZJ3', 'categoryKey': 'KQIY4I2Q' }],
    ['Metamorphic Core Complex', { 'zoteroKey': 'BDFB4KNR', 'categoryKey': 'RMBD6DDR' }],
    ['Metamorphic Facies', { 'zoteroKey': '3IZN6NJP', 'categoryKey': 'G9JSQQRZ' }],
    ['Metasomatism', { 'zoteroKey': '9ZKYFPZJ', 'categoryKey': 'GHSKYH8D' }],
    ['Meteorites', { 'zoteroKey': '3GJ9M3ZS', 'categoryKey': '5CIELCLP' }],
    ['Methane Hydrate', { 'zoteroKey': '9LI6MF7C', 'categoryKey': 'J6DYKAZU' }],
    ['Mianning-Dechang REE Belt', { 'zoteroKey': 'FSTP4N69', 'categoryKey': 'KV2D6RI8' }],
    ['Microaerophilia', { 'zoteroKey': 'HCJV3XF5', 'categoryKey': 'DT6AGGAR' }],
    ['Microbiology', { 'zoteroKey': 'NE5MC5ND', 'categoryKey': '6F3PYY9U' }],
    ['Micropaleontology', { 'zoteroKey': 'LP4YNJ8V', 'categoryKey': '5JCCJ6VI' }],
    ['Mid-Atlantic Ridge', { 'zoteroKey': 'CTAZ4I5G', 'categoryKey': '59QYDB7A' }],
    ['Midcontinental Rift', { 'zoteroKey': 'INX6JXKE', 'categoryKey': 'XYTIRFPI' }],
    ['Migmatite', { 'zoteroKey': 'I5BBI97Z', 'categoryKey': 'YMELCFHI' }],
    ['Mineral Evolution', { 'zoteroKey': 'LNGQFHZV', 'categoryKey': 'XK6ZZUM7' }],
    ['Mineralogy', { 'zoteroKey': 'XZSHHTML', 'categoryKey': 'XK6ZZUM7' }],
    ['Mirovoi Ocean', { 'zoteroKey': 'ETGL28VW', 'categoryKey': 'LXK45IKJ' }],
    ['Modeling', { 'zoteroKey': '3YAWL5NT', 'categoryKey': 'PMPXZKGZ' }],
    ['Mount Weld Complex', { 'zoteroKey': 'QMDBKVBU', 'categoryKey': 'EJABSXMZ' }],
    ['Mozambique Ocean', { 'zoteroKey': '6X7W8ISI', 'categoryKey': 'LXK45IKJ' }],
    ['Mt. Rainier', { 'zoteroKey': '72RD5D8L', 'categoryKey': 'NIM9XJDP' }],
    ['Mt. Vesuvius', { 'zoteroKey': 'FHCGSRUH', 'categoryKey': 'D6LBGDKG' }],
    ['Muskox Intrusion', { 'zoteroKey': '3CBX5IR7', 'categoryKey': 'XYTIRFPI' }],
    ['Mylonite', { 'zoteroKey': 'RP8ZRUS3', 'categoryKey': 'ESLDBDBH' }],
    ['Mylonitization', { 'zoteroKey': 'JSM7SZWW', 'categoryKey': '2X3KB9UK' }],
    ['Natural Disasters', { 'zoteroKey': 'U5LBP2SF', 'categoryKey': 'UBZ96UU9' }],
    ['Nature', { 'zoteroKey': 'J8IE9HTR', 'categoryKey': 'T9YYYJXV' }],
    ['Nd Isotope Geochronology', { 'zoteroKey': 'BP78NY7T', 'categoryKey': 'AHUGIUIX' }],
    ['Nephrite', { 'zoteroKey': 'CW9M5AXW', 'categoryKey': 'J6DYKAZU' }],
    ['Network Analysis', { 'zoteroKey': 'T68FZWUM', 'categoryKey': 'TSJFSNLM' }],
    ['Neutrophilia', { 'zoteroKey': 'L59LPZUL', 'categoryKey': 'DT6AGGAR' }],
    ['North Atlantic Igneous Province', { 'zoteroKey': '5IDYY9CV', 'categoryKey': '59QYDB7A' }],
    ['Northwest Territories', { 'zoteroKey': '4VJTB6AA', 'categoryKey': 'NIM9XJDP' }],
    ['Obduction', { 'zoteroKey': 'LNTGDM8C', 'categoryKey': '2X3KB9UK' }],
    ['Oceanic Core Complex', { 'zoteroKey': 'LIQ7MZFC', 'categoryKey': 'TRDKZRVT' }],
    ['Oceanic Crust', { 'zoteroKey': 'ZVAJX3S7', 'categoryKey': 'TRDKZRVT' }],
    ['Oligocene', { 'zoteroKey': 'NVLTGWPN', 'categoryKey': 'V5VPX2PQ' }],
    ['Olivine', { 'zoteroKey': 'SXMXUWYD', 'categoryKey': 'J6DYKAZU' }],
    ['Ontario', { 'zoteroKey': 'IIGX6ZHI', 'categoryKey': 'NIM9XJDP' }],
    ['Opening of the Arctic Ocean', { 'zoteroKey': 'E3YCUJKU', 'categoryKey': 'VEKG4WYC' }],
    ['Optical Mineralogy', { 'zoteroKey': 'NUTKA5WP', 'categoryKey': 'XK6ZZUM7' }],
    ['Oxidation', { 'zoteroKey': 'AKW5JEPA', 'categoryKey': 'ZD3RMGYZ' }],
    ['Oxide Minerals', { 'zoteroKey': 'QMG45K3I', 'categoryKey': 'J6DYKAZU' }],
    ['Oxygen', { 'zoteroKey': 'BHMD6VA7', 'categoryKey': 'WEYABF24' }],
    ['Oxygen Fugacity', { 'zoteroKey': 'FM7R2YBK', 'categoryKey': 'ZD3RMGYZ' }],
    ['Oxygen Isotope Geochemistry', { 'zoteroKey': '4BRK6SYX', 'categoryKey': 'FJYJM3DI' }],
    ['P-T Boundary', { 'zoteroKey': 'Q47EZECI', 'categoryKey': 'VEKG4WYC' }],
    ['P-T Extinction', { 'zoteroKey': 'HKK8CHDJ', 'categoryKey': 'VEKG4WYC' }],
    ['Paleo-Pacific Ocean', { 'zoteroKey': '2BJWDCXZ', 'categoryKey': 'LXK45IKJ' }],
    ['Paleoproterozoic', { 'zoteroKey': 'GEVJRSMX', 'categoryKey': 'V5VPX2PQ' }],
    ['Pangea', { 'zoteroKey': 'INDHZQPT', 'categoryKey': 'LXK45IKJ' }],
    ['Pannonian Basin', { 'zoteroKey': 'IM472PMI', 'categoryKey': 'IPHGQT5Z' }],
    ['Pannotia', { 'zoteroKey': '74L9N2GU', 'categoryKey': 'LXK45IKJ' }],
    ['Paraná-Etendeka Large Igneous Province', { 'zoteroKey': 'JIRKUGEU', 'categoryKey': '2UYF9GDE' }],
    ['Pedology', { 'zoteroKey': '3G3TL3AD', 'categoryKey': '3GMSUJIY' }],
    ['Pegmatite', { 'zoteroKey': 'IUE6VDK5', 'categoryKey': 'YMELCFHI' }],
    ['Pelagonia', { 'zoteroKey': 'L5SL277M', 'categoryKey': 'IPHGQT5Z' }],
    ['Penokean Orogeny', { 'zoteroKey': 'LHM6TNMD', 'categoryKey': 'VEKG4WYC' }],
    ['Penokee Range', { 'zoteroKey': 'HXZN5QBS', 'categoryKey': 'NIM9XJDP' }],
    ['Peperite', { 'zoteroKey': 'DTH4BUAP', 'categoryKey': 'YE8GL56Y' }],
    ['Peridotite Mylonite', { 'zoteroKey': 'BY5RI858', 'categoryKey': 'ESLDBDBH' }],
    ['Permafrost', { 'zoteroKey': 'GMR6NF5L', 'categoryKey': 'T9YYYJXV' }],
    ['Permian', { 'zoteroKey': 'Z7UA4TYN', 'categoryKey': 'V5VPX2PQ' }],
    ['Petrology', { 'zoteroKey': 'DJ7A26V3', 'categoryKey': 'G9JSQQRZ' }],
    ['PGZ', { 'zoteroKey': '5KNV3YCL', 'categoryKey': '2X3KB9UK' }],
    ['Photosynthesis', { 'zoteroKey': '3G27ES66', 'categoryKey': 'DT6AGGAR' }],
    ['Phreatomagmatic Eruption', { 'zoteroKey': 'BBMHTFRT', 'categoryKey': 'GHSKYH8D' }],
    ['Piacenzian', { 'zoteroKey': 'JFJBHXXJ', 'categoryKey': 'V5VPX2PQ' }],
    ['Pillow Basalt', { 'zoteroKey': '66RV5PED', 'categoryKey': 'YMELCFHI' }],
    ['Plane-polarized Light', { 'zoteroKey': 'VXKNHA5Y', 'categoryKey': 'XK6ZZUM7' }],
    ['Plate Reconstruction', { 'zoteroKey': 'VF6BQF4R', 'categoryKey': 'PMPXZKGZ' }],
    ['Plate Reorganization', { 'zoteroKey': '5XG5DQKP', 'categoryKey': '2X3KB9UK' }],
    ['Plinian Eruption', { 'zoteroKey': 'ZYYFWG5W', 'categoryKey': 'GHSKYH8D' }],
    ['Pull-apart Basin', { 'zoteroKey': 'XICDQAIG', 'categoryKey': 'TRDKZRVT' }],
    ['Pyrenees', { 'zoteroKey': 'ZL8FUH62', 'categoryKey': 'D6LBGDKG' }],
    ['Pyroclastic Flows', { 'zoteroKey': 'DA33V94F', 'categoryKey': 'YE8GL56Y' }],
    ['Pyroxene', { 'zoteroKey': 'KLID8ILZ', 'categoryKey': 'J6DYKAZU' }],
    ['Radiolarite', { 'zoteroKey': '547K3JZ9', 'categoryKey': 'SR38G92F' }],
    ['Reduction', { 'zoteroKey': 'CTQR7LIG', 'categoryKey': 'ZD3RMGYZ' }],
    ['Research', { 'zoteroKey': 'P6BQUK6G', 'categoryKey': 'M95SG6D4' }],
    ['Reykjanes Peninsula', { 'zoteroKey': '9CGAGWEU', 'categoryKey': 'D6LBGDKG' }],
    ['Rhine Graben', { 'zoteroKey': 'U65R7VXL', 'categoryKey': 'IPHGQT5Z' }],
    ['Rhine-Bresse Transfer Zone', { 'zoteroKey': '3TAJ6APP', 'categoryKey': 'IPHGQT5Z' }],
    ['Rhodopia', { 'zoteroKey': 'NISY5N2Y', 'categoryKey': 'IPHGQT5Z' }],
    ['Rhyolite', { 'zoteroKey': 'EFERVHHI', 'categoryKey': 'YMELCFHI' }],
    ['Rodinia', { 'zoteroKey': '2WZXZZJY', 'categoryKey': 'LXK45IKJ' }],
    ['Saharan Metacraton', { 'zoteroKey': 'XPHLIQYM', 'categoryKey': 'LXK45IKJ' }],
    ['Salt Tectonics', { 'zoteroKey': 'F4QAJ88N', 'categoryKey': 'GHSKYH8D' }],
    ['Sample Targeting', { 'zoteroKey': 'A4YJNX64', 'categoryKey': 'FJYJM3DI' }],
    ['Sandstone', { 'zoteroKey': 'CVW6LT8N', 'categoryKey': 'SR38G92F' }],
    ['Santa Cruz Mountains', { 'zoteroKey': '7TACRSWX', 'categoryKey': 'NIM9XJDP' }],
    ['Secular Evolution of Earth\'s Atmosphere', { 'zoteroKey': '7XMKDM64', 'categoryKey': '5CIELCLP' }],
    ['SEM', { 'zoteroKey': 'SD36N9MY', 'categoryKey': 'XK6ZZUM7' }],
    ['Serpentinite Diapir', { 'zoteroKey': '64HKAEYX', 'categoryKey': 'TRDKZRVT' }],
    ['Sheeted Dikes', { 'zoteroKey': '6JFQKBBY', 'categoryKey': 'TRDKZRVT' }],
    ['Shuksan Greenschist', { 'zoteroKey': 'B8S25JNA', 'categoryKey': 'EJABSXMZ' }],
    ['Slab Roll-back', { 'zoteroKey': '7ZYNQ4YV', 'categoryKey': '2X3KB9UK' }],
    ['Snowball Earth', { 'zoteroKey': '655BLZVS', 'categoryKey': 'VEKG4WYC' }],
    ['Soapstone', { 'zoteroKey': '626T9ZYR', 'categoryKey': 'ESLDBDBH' }],
    ['Soil', { 'zoteroKey': 'M39HVUVL', 'categoryKey': 'GHSKYH8D' }],
    ['Soil Development', { 'zoteroKey': 'II8HYKMW', 'categoryKey': 'GHSKYH8D' }],
    ['Solar Flare', { 'zoteroKey': 'REG8GFX3', 'categoryKey': '4X74KAHT' }],
    ['South Africa', { 'zoteroKey': 'UK32HL9C', 'categoryKey': 'LAFQUF5S' }],
    ['Space Weather', { 'zoteroKey': 'NYLSUYDE', 'categoryKey': '4X74KAHT' }],
    ['Spatsizi Plateau', { 'zoteroKey': 'S8BBWXQW', 'categoryKey': 'NIM9XJDP' }],
    ['SR-type Ignimbrites', { 'zoteroKey': '353374G8', 'categoryKey': 'YMELCFHI' }],
    ['St. Peter St. Paul Rocks', { 'zoteroKey': 'NGWDYGKB', 'categoryKey': 'LJ6Z2LH5' }],
    ['Steinmann Trinity', { 'zoteroKey': 'IS5D45RK', 'categoryKey': 'TRDKZRVT' }],
    ['Stikine River', { 'zoteroKey': 'BFIQGGLQ', 'categoryKey': 'KQIY4I2Q' }],
    ['Stratigraphy', { 'zoteroKey': 'YCCNNFKA', 'categoryKey': 'JS85BYXK' }],
    ['Strike-slip Fault', { 'zoteroKey': 'YD9SH9VP', 'categoryKey': 'TRDKZRVT' }],
    ['Sub-continental Mantle Lithosphere', { 'zoteroKey': '72WXD6BI', 'categoryKey': 'TRDKZRVT' }],
    ['Subducted Slab', { 'zoteroKey': 'D5XMH5ET', 'categoryKey': 'TRDKZRVT' }],
    ['Subseafloor', { 'zoteroKey': '7FCHPL4Q', 'categoryKey': 'JU5MHYTT' }],
    ['Sudbury Impact Event', { 'zoteroKey': 'IDRKFMAD', 'categoryKey': 'VEKG4WYC' }],
    ['Sunspots', { 'zoteroKey': 'H6IYLAHL', 'categoryKey': '4X74KAHT' }],
    ['Supercontinent', { 'zoteroKey': '5L48C25Y', 'categoryKey': 'TRDKZRVT' }],
    ['Surtseyan Eruption', { 'zoteroKey': 'XL7MB7UQ', 'categoryKey': 'GHSKYH8D' }],
    ['Suture', { 'zoteroKey': 'MIAJUR3N', 'categoryKey': 'TRDKZRVT' }],
    ['Syncline', { 'zoteroKey': 'WN77TE3S', 'categoryKey': 'TRDKZRVT' }],
    ['Tectonic Escape', { 'zoteroKey': 'IZK5LDDJ', 'categoryKey': 'GHSKYH8D' }],
    ['Tectonic Sliver', { 'zoteroKey': 'PRBTGF53', 'categoryKey': 'TRDKZRVT' }],
    ['Terrane', { 'zoteroKey': 'EYMLPXAP', 'categoryKey': 'TRDKZRVT' }],
    ['Terrane Accretion', { 'zoteroKey': '4NWR7WGA', 'categoryKey': '2X3KB9UK' }],
    ['Terroir', { 'zoteroKey': 'F2EC43A6', 'categoryKey': 'T9YYYJXV' }],
    ['Tethys Ocean', { 'zoteroKey': 'YBJPU5G8', 'categoryKey': 'LXK45IKJ' }],
    ['The Great Dying', { 'zoteroKey': 'UYYTISB7', 'categoryKey': 'VEKG4WYC' }],
    ['Thin Section', { 'zoteroKey': 'JRI3CYT6', 'categoryKey': 'G9JSQQRZ' }],
    ['Thin Section Microscopy', { 'zoteroKey': 'KH7MXIRR', 'categoryKey': 'XK6ZZUM7' }],
    ['Thrust Fault', { 'zoteroKey': 'C8U2XNX3', 'categoryKey': 'TRDKZRVT' }],
    ['Tonian', { 'zoteroKey': '4IZT9G7X', 'categoryKey': 'V5VPX2PQ' }],
    ['Transform Fault', { 'zoteroKey': 'FXJJS7VB', 'categoryKey': 'TRDKZRVT' }],
    ['Transtensional Basin', { 'zoteroKey': '6UN33B5H', 'categoryKey': 'TRDKZRVT' }],
    ['Tundra', { 'zoteroKey': '56CTGCKX', 'categoryKey': 'JU5MHYTT' }],
    ['Twin Sisters Dunite', { 'zoteroKey': '5EGBSB6S', 'categoryKey': 'EJABSXMZ' }],
    ['Ultra-mylonite', { 'zoteroKey': 'J8DXD4KY', 'categoryKey': 'ESLDBDBH' }],
    ['Ultramafic', { 'zoteroKey': 'M6U5B4VW', 'categoryKey': 'G9JSQQRZ' }],
    ['Uplift', { 'zoteroKey': '3MJ7UCDD', 'categoryKey': 'GHSKYH8D' }],
    ['Vestmannaeyjar', { 'zoteroKey': 'BB2CGXHV', 'categoryKey': 'D6LBGDKG' }],
    ['Volcanic Ash', { 'zoteroKey': 'GTBSEHR7', 'categoryKey': 'YE8GL56Y' }],
    ['Volcanic Hazards', { 'zoteroKey': 'ULCTEU8W', 'categoryKey': 'UBZ96UU9' }],
    ['Wales', { 'zoteroKey': 'IUVY64QE', 'categoryKey': 'D6LBGDKG' }],
    ['Weathering', { 'zoteroKey': '4VPAAQUZ', 'categoryKey': 'GHSKYH8D' }],
    ['Welded Tuff', { 'zoteroKey': 'PV7YX397', 'categoryKey': 'YMELCFHI' }],
    ['Wilson Cycle', { 'zoteroKey': '3BGZEZ93', 'categoryKey': '2X3KB9UK' }],
    ['Wisconsin', { 'zoteroKey': 'NRBCK6ZX', 'categoryKey': 'NIM9XJDP' }],
    ['Wrangell Island', { 'zoteroKey': 'QGWPW9TI', 'categoryKey': 'NIM9XJDP' }],
    ['Wrangellia', { 'zoteroKey': 'UKM3CVQA', 'categoryKey': 'LXK45IKJ' }],
    ['Wyoming Craton', { 'zoteroKey': 'K6AXED7M', 'categoryKey': 'XYTIRFPI' }],
    ['X-ray Diffraction', { 'zoteroKey': 'ULEHTV75', 'categoryKey': 'FJYJM3DI' }],
    ['Yellowstone Supervolcano', { 'zoteroKey': 'JPL2SDYA', 'categoryKey': 'XYTIRFPI' }],
    ['Zechstein Sea', { 'zoteroKey': 'ZPM2FALN', 'categoryKey': 'LXK45IKJ' }],
    ['Zircon', { 'zoteroKey': 'R6PH7PJM', 'categoryKey': 'J6DYKAZU' }]
  ])
};