#!/bin/bash

# bash (re)start script
# - makes sure correct version of node is running
# - checks to see if pm2 and redis are already running, and if so, shuts them down
# - starts redis-server using config file with daemonize=yes
# - checks for a successful client connection to redis-server using the redis-cli
# - if connection has been established, server is (re)started using pm2 in cluster mode, with some options for graceful shutdown/startup
# - if connection cannot be established, exit with error
# - use your own redis and server directory locations

REDIS_DIR="~/workspace/redis-stable"
SERVER_DIR="~/workspace"

# - required on my particular VM setup, which keeps resetting the node version
nvm use 14.15.1

[ ! -z "$(ps -ax | grep pm2 | grep -v grep)" ] && pm2 stop "${SERVER_DIR}/server.js";
[ ! -z "$(ps -ax | grep redis | grep -v grep)" ] && redis-cli shutdown;

redis-server "${REDIS_DIR}/redis.conf" &

if [[ `redis-cli ping` = 'PONG' ]]; then 
  pm2 start "${SERVER_DIR}/server.js" -i 3 --wait-ready --listen-timeout 3000 --kill-timeout 6000 --update-env
else
  echo "Redis server is not running."
  exit 111
fi
